"""Baseline schema generated from the biz2bricks_core models

Revision ID: 0001
Revises:
Create Date: 2026-09-20

This replaces migrations 001-004, which were never executed against any
database. Every environment was built by Base.metadata.create_all at service
startup, and the old chain had drifted badly from the models: it declared an
older generation of users/documents/organizations/folders (a users table with
no password_hash, for example), created five usage tables no model references,
and omitted the current usage-tracking and RAG cache tables entirely. Running
it would have produced a database the application could not start against.

Because nothing was ever migrated, that chain recorded no real history and was
safe to replace with a baseline autogenerated from the models.

Existing databases already match this baseline and must be stamped, not
upgraded:

    alembic stamp head

Fresh databases get the whole schema from `alembic upgrade head`.
"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # rag_query_cache declares a vector(768) column, so the extension has to
    # exist before any table is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_used', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('refresh_token', sa.String(length=36), nullable=True),
    sa.Column('refresh_expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_index('idx_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('idx_sessions_org_is_active', 'sessions', ['organization_id', 'is_active'], unique=False)
    op.create_index('idx_sessions_org_user', 'sessions', ['organization_id', 'user_id'], unique=False)
    op.create_index('idx_sessions_organization_id', 'sessions', ['organization_id'], unique=False)
    op.create_index('idx_sessions_refresh_token', 'sessions', ['refresh_token'], unique=False)
    op.create_table('subscription_tiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('monthly_token_limit', sa.BigInteger(), nullable=False),
    sa.Column('monthly_llamaparse_pages', sa.Integer(), nullable=False),
    sa.Column('monthly_file_search_queries', sa.Integer(), nullable=False),
    sa.Column('storage_gb_limit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('requests_per_minute', sa.Integer(), nullable=True),
    sa.Column('requests_per_day', sa.Integer(), nullable=True),
    sa.Column('max_file_size_mb', sa.Integer(), nullable=True),
    sa.Column('max_concurrent_jobs', sa.Integer(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('monthly_price_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('annual_price_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stripe_product_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_monthly_price_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_annual_price_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tier')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('plan_type', sa.String(length=50), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('subscription_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_tiers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_organizations_active_created', 'organizations', ['is_active', 'created_at'], unique=False)
    op.create_index('idx_organizations_created_at', 'organizations', ['created_at'], unique=False)
    op.create_index('idx_organizations_is_active', 'organizations', ['is_active'], unique=False)
    op.create_index('idx_organizations_plan_id', 'organizations', ['plan_id'], unique=False)
    op.create_table('bulk_jobs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('folder_name', sa.String(length=255), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('total_documents', sa.Integer(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('total_llamaparse_pages', sa.Integer(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'partial_failure', 'failed', 'cancelled')", name='chk_bulk_jobs_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bulk_jobs_created_at', 'bulk_jobs', ['created_at'], unique=False)
    op.create_index('idx_bulk_jobs_org_folder', 'bulk_jobs', ['organization_id', 'folder_name'], unique=False)
    op.create_index('idx_bulk_jobs_org_id', 'bulk_jobs', ['organization_id'], unique=False)
    op.create_index('idx_bulk_jobs_org_status', 'bulk_jobs', ['organization_id', 'status'], unique=False)
    op.create_index('idx_bulk_jobs_source_path', 'bulk_jobs', ['source_path'], unique=False)
    op.create_index('idx_bulk_jobs_status', 'bulk_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_bulk_jobs_organization_id'), 'bulk_jobs', ['organization_id'], unique=False)
    op.create_table('conversation_summaries',
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_topics', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('documents_discussed', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('queries_count', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("agent_type IN ('document', 'sheets')", name='chk_conversation_summaries_agent_type'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('idx_summaries_created_at', 'conversation_summaries', ['created_at'], unique=False)
    op.create_index('idx_summaries_org_id', 'conversation_summaries', ['organization_id'], unique=False)
    op.create_index('idx_summaries_org_user', 'conversation_summaries', ['organization_id', 'user_id'], unique=False)
    op.create_index('idx_summaries_user_agent', 'conversation_summaries', ['user_id', 'agent_type'], unique=False)
    op.create_index('idx_summaries_user_id', 'conversation_summaries', ['user_id'], unique=False)
    op.create_index(op.f('ix_conversation_summaries_organization_id'), 'conversation_summaries', ['organization_id'], unique=False)
    op.create_table('document_generations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('generation_type', sa.String(length=50), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("generation_type IN ('summary', 'faqs', 'questions', 'all')", name='chk_document_generations_type'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_generations_content', 'document_generations', ['content'], unique=False, postgresql_using='gin')
    op.create_index('idx_generations_created_at', 'document_generations', ['created_at'], unique=False)
    op.create_index('idx_generations_document_name', 'document_generations', ['document_name'], unique=False)
    op.create_index('idx_generations_org_cache', 'document_generations', ['organization_id', 'document_name', 'generation_type', 'model'], unique=False)
    op.create_index('idx_generations_org_id', 'document_generations', ['organization_id'], unique=False)
    op.create_index('idx_generations_session', 'document_generations', ['session_id'], unique=False)
    op.create_index(op.f('ix_document_generations_organization_id'), 'document_generations', ['organization_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('folder_id', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('parsed_path', sa.Text(), nullable=True),
    sa.Column('parsed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_created_at', 'documents', ['created_at'], unique=False)
    op.create_index('idx_documents_file_hash', 'documents', ['file_hash'], unique=False)
    op.create_index('idx_documents_filename', 'documents', ['filename'], unique=False)
    op.create_index('idx_documents_folder_id', 'documents', ['folder_id'], unique=False)
    op.create_index('idx_documents_metadata', 'documents', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_documents_org_active', 'documents', ['organization_id', 'is_active'], unique=False)
    op.create_index('idx_documents_org_filename', 'documents', ['organization_id', 'filename'], unique=False)
    op.create_index('idx_documents_org_folder', 'documents', ['organization_id', 'folder_id'], unique=False)
    op.create_index('idx_documents_organization_id', 'documents', ['organization_id'], unique=False)
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False)
    op.create_index('idx_documents_storage_path', 'documents', ['storage_path'], unique=False)
    op.create_index('idx_documents_uploaded_by', 'documents', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=True)
    op.create_table('file_search_stores',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('gemini_store_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gcp_project', sa.String(length=255), nullable=True),
    sa.Column('active_documents_count', sa.Integer(), nullable=False),
    sa.Column('total_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive', 'error')", name='chk_file_search_stores_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gemini_store_id')
    )
    op.create_index('idx_file_stores_display_name', 'file_search_stores', ['display_name'], unique=False)
    op.create_index('idx_file_stores_gemini_id', 'file_search_stores', ['gemini_store_id'], unique=False)
    op.create_index('idx_file_stores_status', 'file_search_stores', ['status'], unique=False)
    op.create_index(op.f('ix_file_search_stores_organization_id'), 'file_search_stores', ['organization_id'], unique=True)
    op.create_table('folders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_folder_id', sa.String(length=36), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_folders_org_is_active', 'folders', ['organization_id', 'is_active'], unique=False)
    op.create_index('idx_folders_org_name', 'folders', ['organization_id', 'name'], unique=False)
    op.create_index('idx_folders_org_parent', 'folders', ['organization_id', 'parent_folder_id'], unique=False)
    op.create_index('idx_folders_organization_id', 'folders', ['organization_id'], unique=False)
    op.create_index('idx_folders_parent_id', 'folders', ['parent_folder_id'], unique=False)
    op.create_index('idx_folders_path', 'folders', ['path'], unique=False)
    op.create_table('memory_entries',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('namespace', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'namespace', 'key', name='uq_memory_org_namespace_key')
    )
    op.create_index('idx_memory_data', 'memory_entries', ['data'], unique=False, postgresql_using='gin')
    op.create_index('idx_memory_namespace', 'memory_entries', ['namespace'], unique=False)
    op.create_index('idx_memory_namespace_key', 'memory_entries', ['namespace', 'key'], unique=False)
    op.create_index('idx_memory_org_id', 'memory_entries', ['organization_id'], unique=False)
    op.create_index('idx_memory_org_namespace', 'memory_entries', ['organization_id', 'namespace'], unique=False)
    op.create_index(op.f('ix_memory_entries_organization_id'), 'memory_entries', ['organization_id'], unique=False)
    op.create_table('organization_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.String(length=255), nullable=False),
    sa.Column('tier_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('billing_cycle', sa.String(length=20), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=False),
    sa.Column('tokens_used_this_period', sa.BigInteger(), nullable=True),
    sa.Column('llamaparse_pages_used', sa.Integer(), nullable=True),
    sa.Column('file_search_queries_used', sa.Integer(), nullable=True),
    sa.Column('storage_used_bytes', sa.BigInteger(), nullable=True),
    sa.Column('monthly_token_limit', sa.BigInteger(), nullable=False),
    sa.Column('monthly_llamaparse_pages_limit', sa.Integer(), nullable=False),
    sa.Column('monthly_file_search_queries_limit', sa.Integer(), nullable=False),
    sa.Column('storage_limit_bytes', sa.BigInteger(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tier_id'], ['subscription_tiers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_index('idx_org_sub_period_end', 'organization_subscriptions', ['current_period_end'], unique=False)
    op.create_index('idx_org_sub_status', 'organization_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_organization_subscriptions_stripe_customer_id'), 'organization_subscriptions', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('ix_organization_subscriptions_stripe_subscription_id'), 'organization_subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('complexity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('output_path', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('processing', 'completed', 'failed')", name='chk_processing_jobs_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_document_hash', 'processing_jobs', ['document_hash'], unique=False)
    op.create_index('idx_jobs_file_name', 'processing_jobs', ['file_name'], unique=False)
    op.create_index('idx_jobs_org_cache_lookup', 'processing_jobs', ['organization_id', 'document_hash', 'model', 'status'], unique=False, postgresql_where="status = 'completed'")
    op.create_index('idx_jobs_org_id', 'processing_jobs', ['organization_id'], unique=False)
    op.create_index('idx_jobs_started_at', 'processing_jobs', ['started_at'], unique=False)
    op.create_index('idx_jobs_status', 'processing_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_processing_jobs_organization_id'), 'processing_jobs', ['organization_id'], unique=False)
    op.create_table('rag_query_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.String(length=255), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('query_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('folder_filter', sa.String(length=255), nullable=True),
    sa.Column('file_filter', sa.String(length=255), nullable=True),
    sa.Column('search_mode', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rag_cache_org_file', 'rag_query_cache', ['org_id', 'file_filter'], unique=False)
    op.create_index('idx_rag_cache_org_folder', 'rag_query_cache', ['org_id', 'folder_filter'], unique=False)
    op.create_index(op.f('ix_rag_query_cache_org_id'), 'rag_query_cache', ['org_id'], unique=False)
    op.create_table('usage_aggregations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.String(length=255), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('total_tokens', sa.BigInteger(), nullable=True),
    sa.Column('total_input_tokens', sa.BigInteger(), nullable=True),
    sa.Column('total_output_tokens', sa.BigInteger(), nullable=True),
    sa.Column('total_cached_tokens', sa.BigInteger(), nullable=True),
    sa.Column('document_agent_tokens', sa.BigInteger(), nullable=True),
    sa.Column('sheets_agent_tokens', sa.BigInteger(), nullable=True),
    sa.Column('rag_tokens', sa.BigInteger(), nullable=True),
    sa.Column('llamaparse_pages', sa.Integer(), nullable=True),
    sa.Column('file_search_queries', sa.Integer(), nullable=True),
    sa.Column('storage_delta_bytes', sa.BigInteger(), nullable=True),
    sa.Column('total_cost_usd', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=True),
    sa.Column('successful_requests', sa.Integer(), nullable=True),
    sa.Column('failed_requests', sa.Integer(), nullable=True),
    sa.Column('breakdown_by_feature', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('breakdown_by_model', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('aggregated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'period_type', 'period_start', name='uq_usage_agg_org_period')
    )
    op.create_index('idx_usage_agg_org_period', 'usage_aggregations', ['organization_id', 'period_type', 'period_start'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('preferred_summary_length', sa.Integer(), nullable=False),
    sa.Column('preferred_faq_count', sa.Integer(), nullable=False),
    sa.Column('preferred_question_count', sa.Integer(), nullable=False),
    sa.Column('custom_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('idx_user_prefs_org_id', 'user_preferences', ['organization_id'], unique=False)
    op.create_index('idx_user_prefs_org_user', 'user_preferences', ['organization_id', 'user_id'], unique=False)
    op.create_index('idx_user_prefs_updated', 'user_preferences', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_preferences_organization_id'), 'user_preferences', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_org_email', 'users', ['organization_id', 'email'], unique=False)
    op.create_index('idx_users_org_is_active', 'users', ['organization_id', 'is_active'], unique=False)
    op.create_index('idx_users_org_username', 'users', ['organization_id', 'username'], unique=False)
    op.create_index('idx_users_organization_id', 'users', ['organization_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_document_hash', 'audit_logs', ['document_hash'], unique=False)
    op.create_index('idx_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_logs_event_type', 'audit_logs', ['event_type'], unique=False)
    op.create_index('idx_audit_logs_file_name', 'audit_logs', ['file_name'], unique=False)
    op.create_index('idx_audit_logs_job_id', 'audit_logs', ['job_id'], unique=False)
    op.create_index('idx_audit_logs_org_id', 'audit_logs', ['organization_id'], unique=False)
    op.create_index('idx_audit_logs_org_type_created', 'audit_logs', ['organization_id', 'entity_type', 'created_at'], unique=False)
    op.create_index('idx_audit_logs_org_user_created', 'audit_logs', ['organization_id', 'user_id', 'created_at'], unique=False)
    op.create_index('idx_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('bulk_job_documents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('bulk_job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('original_path', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('parsed_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('parse_time_ms', sa.Integer(), nullable=True),
    sa.Column('index_time_ms', sa.Integer(), nullable=True),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('total_time_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', sa.Integer(), nullable=False),
    sa.Column('llamaparse_pages', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'parsing', 'parsed', 'indexing', 'indexed', 'generating', 'completed', 'failed', 'skipped')", name='chk_bulk_job_documents_status'),
    sa.ForeignKeyConstraint(['bulk_job_id'], ['bulk_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bulk_job_docs_content_hash', 'bulk_job_documents', ['content_hash'], unique=False)
    op.create_index('idx_bulk_job_docs_filename', 'bulk_job_documents', ['original_filename'], unique=False)
    op.create_index('idx_bulk_job_docs_job_id', 'bulk_job_documents', ['bulk_job_id'], unique=False)
    op.create_index('idx_bulk_job_docs_job_status', 'bulk_job_documents', ['bulk_job_id', 'status'], unique=False)
    op.create_index('idx_bulk_job_docs_status', 'bulk_job_documents', ['status'], unique=False)
    op.create_index(op.f('ix_bulk_job_documents_bulk_job_id'), 'bulk_job_documents', ['bulk_job_id'], unique=False)
    op.create_table('document_folders',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('folder_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_folder_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('total_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['document_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['file_search_stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'parent_folder_id', 'folder_name', name='uq_folder_org_parent_name')
    )
    op.create_index('idx_doc_folders_name', 'document_folders', ['folder_name'], unique=False)
    op.create_index('idx_doc_folders_org_id', 'document_folders', ['organization_id'], unique=False)
    op.create_index('idx_doc_folders_org_name', 'document_folders', ['organization_id', 'folder_name'], unique=False)
    op.create_index('idx_doc_folders_parent', 'document_folders', ['parent_folder_id'], unique=False)
    op.create_index('idx_doc_folders_store_id', 'document_folders', ['store_id'], unique=False)
    op.create_index(op.f('ix_document_folders_organization_id'), 'document_folders', ['organization_id'], unique=False)
    op.create_index(op.f('ix_document_folders_parent_folder_id'), 'document_folders', ['parent_folder_id'], unique=False)
    op.create_index(op.f('ix_document_folders_store_id'), 'document_folders', ['store_id'], unique=False)
    op.create_table('intelligence_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('folder_id', sa.String(length=36), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('date_range_start', sa.Date(), nullable=True),
    sa.Column('date_range_end', sa.Date(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('document_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('extracted_record_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('charts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('excel_path', sa.String(length=500), nullable=True),
    sa.Column('json_path', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_intelligence_reports_created_at', 'intelligence_reports', ['created_at'], unique=False)
    op.create_index('idx_intelligence_reports_folder_id', 'intelligence_reports', ['folder_id'], unique=False)
    op.create_index('idx_intelligence_reports_org_folder', 'intelligence_reports', ['organization_id', 'folder_id'], unique=False)
    op.create_index('idx_intelligence_reports_org_id', 'intelligence_reports', ['organization_id'], unique=False)
    op.create_index('idx_intelligence_reports_org_status', 'intelligence_reports', ['organization_id', 'status'], unique=False)
    op.create_index('idx_intelligence_reports_org_type', 'intelligence_reports', ['organization_id', 'report_type'], unique=False)
    op.create_index('idx_intelligence_reports_report_type', 'intelligence_reports', ['report_type'], unique=False)
    op.create_index('idx_intelligence_reports_status', 'intelligence_reports', ['status'], unique=False)
    op.create_table('resource_usage_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resource_org_type', 'resource_usage_records', ['organization_id', 'resource_type', 'created_at'], unique=False)
    op.create_table('token_usage_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('feature', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=True),
    sa.Column('input_cost_usd', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('output_cost_usd', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('total_cost_usd', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index('idx_usage_org_created', 'token_usage_records', ['organization_id', 'created_at'], unique=False)
    op.create_index('idx_usage_org_feature', 'token_usage_records', ['organization_id', 'feature', 'created_at'], unique=False)
    op.create_index(op.f('ix_token_usage_records_created_at'), 'token_usage_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_token_usage_records_feature'), 'token_usage_records', ['feature'], unique=False)
    op.create_index(op.f('ix_token_usage_records_session_id'), 'token_usage_records', ['session_id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_token_usage_records_session_id'), table_name='token_usage_records')
    op.drop_index(op.f('ix_token_usage_records_feature'), table_name='token_usage_records')
    op.drop_index(op.f('ix_token_usage_records_created_at'), table_name='token_usage_records')
    op.drop_index('idx_usage_org_feature', table_name='token_usage_records')
    op.drop_index('idx_usage_org_created', table_name='token_usage_records')
    op.drop_table('token_usage_records')
    op.drop_index('idx_resource_org_type', table_name='resource_usage_records')
    op.drop_table('resource_usage_records')
    op.drop_index('idx_intelligence_reports_status', table_name='intelligence_reports')
    op.drop_index('idx_intelligence_reports_report_type', table_name='intelligence_reports')
    op.drop_index('idx_intelligence_reports_org_type', table_name='intelligence_reports')
    op.drop_index('idx_intelligence_reports_org_status', table_name='intelligence_reports')
    op.drop_index('idx_intelligence_reports_org_id', table_name='intelligence_reports')
    op.drop_index('idx_intelligence_reports_org_folder', table_name='intelligence_reports')
    op.drop_index('idx_intelligence_reports_folder_id', table_name='intelligence_reports')
    op.drop_index('idx_intelligence_reports_created_at', table_name='intelligence_reports')
    op.drop_table('intelligence_reports')
    op.drop_index(op.f('ix_document_folders_store_id'), table_name='document_folders')
    op.drop_index(op.f('ix_document_folders_parent_folder_id'), table_name='document_folders')
    op.drop_index(op.f('ix_document_folders_organization_id'), table_name='document_folders')
    op.drop_index('idx_doc_folders_store_id', table_name='document_folders')
    op.drop_index('idx_doc_folders_parent', table_name='document_folders')
    op.drop_index('idx_doc_folders_org_name', table_name='document_folders')
    op.drop_index('idx_doc_folders_org_id', table_name='document_folders')
    op.drop_index('idx_doc_folders_name', table_name='document_folders')
    op.drop_table('document_folders')
    op.drop_index(op.f('ix_bulk_job_documents_bulk_job_id'), table_name='bulk_job_documents')
    op.drop_index('idx_bulk_job_docs_status', table_name='bulk_job_documents')
    op.drop_index('idx_bulk_job_docs_job_status', table_name='bulk_job_documents')
    op.drop_index('idx_bulk_job_docs_job_id', table_name='bulk_job_documents')
    op.drop_index('idx_bulk_job_docs_filename', table_name='bulk_job_documents')
    op.drop_index('idx_bulk_job_docs_content_hash', table_name='bulk_job_documents')
    op.drop_table('bulk_job_documents')
    op.drop_index('idx_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_org_user_created', table_name='audit_logs')
    op.drop_index('idx_audit_logs_org_type_created', table_name='audit_logs')
    op.drop_index('idx_audit_logs_org_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_job_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_file_name', table_name='audit_logs')
    op.drop_index('idx_audit_logs_event_type', table_name='audit_logs')
    op.drop_index('idx_audit_logs_entity', table_name='audit_logs')
    op.drop_index('idx_audit_logs_document_hash', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_users_organization_id', table_name='users')
    op.drop_index('idx_users_org_username', table_name='users')
    op.drop_index('idx_users_org_is_active', table_name='users')
    op.drop_index('idx_users_org_email', table_name='users')
    op.drop_index('idx_users_is_active', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_preferences_organization_id'), table_name='user_preferences')
    op.drop_index('idx_user_prefs_updated', table_name='user_preferences')
    op.drop_index('idx_user_prefs_org_user', table_name='user_preferences')
    op.drop_index('idx_user_prefs_org_id', table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index('idx_usage_agg_org_period', table_name='usage_aggregations')
    op.drop_table('usage_aggregations')
    op.drop_index(op.f('ix_rag_query_cache_org_id'), table_name='rag_query_cache')
    op.drop_index('idx_rag_cache_org_folder', table_name='rag_query_cache')
    op.drop_index('idx_rag_cache_org_file', table_name='rag_query_cache')
    op.drop_table('rag_query_cache')
    op.drop_index(op.f('ix_processing_jobs_organization_id'), table_name='processing_jobs')
    op.drop_index('idx_jobs_status', table_name='processing_jobs')
    op.drop_index('idx_jobs_started_at', table_name='processing_jobs')
    op.drop_index('idx_jobs_org_id', table_name='processing_jobs')
    op.drop_index('idx_jobs_org_cache_lookup', table_name='processing_jobs', postgresql_where="status = 'completed'")
    op.drop_index('idx_jobs_file_name', table_name='processing_jobs')
    op.drop_index('idx_jobs_document_hash', table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_organization_subscriptions_stripe_subscription_id'), table_name='organization_subscriptions')
    op.drop_index(op.f('ix_organization_subscriptions_stripe_customer_id'), table_name='organization_subscriptions')
    op.drop_index('idx_org_sub_status', table_name='organization_subscriptions')
    op.drop_index('idx_org_sub_period_end', table_name='organization_subscriptions')
    op.drop_table('organization_subscriptions')
    op.drop_index(op.f('ix_memory_entries_organization_id'), table_name='memory_entries')
    op.drop_index('idx_memory_org_namespace', table_name='memory_entries')
    op.drop_index('idx_memory_org_id', table_name='memory_entries')
    op.drop_index('idx_memory_namespace_key', table_name='memory_entries')
    op.drop_index('idx_memory_namespace', table_name='memory_entries')
    op.drop_index('idx_memory_data', table_name='memory_entries', postgresql_using='gin')
    op.drop_table('memory_entries')
    op.drop_index('idx_folders_path', table_name='folders')
    op.drop_index('idx_folders_parent_id', table_name='folders')
    op.drop_index('idx_folders_organization_id', table_name='folders')
    op.drop_index('idx_folders_org_parent', table_name='folders')
    op.drop_index('idx_folders_org_name', table_name='folders')
    op.drop_index('idx_folders_org_is_active', table_name='folders')
    op.drop_table('folders')
    op.drop_index(op.f('ix_file_search_stores_organization_id'), table_name='file_search_stores')
    op.drop_index('idx_file_stores_status', table_name='file_search_stores')
    op.drop_index('idx_file_stores_gemini_id', table_name='file_search_stores')
    op.drop_index('idx_file_stores_display_name', table_name='file_search_stores')
    op.drop_table('file_search_stores')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_index('idx_documents_uploaded_by', table_name='documents')
    op.drop_index('idx_documents_storage_path', table_name='documents')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_index('idx_documents_organization_id', table_name='documents')
    op.drop_index('idx_documents_org_folder', table_name='documents')
    op.drop_index('idx_documents_org_filename', table_name='documents')
    op.drop_index('idx_documents_org_active', table_name='documents')
    op.drop_index('idx_documents_metadata', table_name='documents', postgresql_using='gin')
    op.drop_index('idx_documents_folder_id', table_name='documents')
    op.drop_index('idx_documents_filename', table_name='documents')
    op.drop_index('idx_documents_file_hash', table_name='documents')
    op.drop_index('idx_documents_created_at', table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_document_generations_organization_id'), table_name='document_generations')
    op.drop_index('idx_generations_session', table_name='document_generations')
    op.drop_index('idx_generations_org_id', table_name='document_generations')
    op.drop_index('idx_generations_org_cache', table_name='document_generations')
    op.drop_index('idx_generations_document_name', table_name='document_generations')
    op.drop_index('idx_generations_created_at', table_name='document_generations')
    op.drop_index('idx_generations_content', table_name='document_generations', postgresql_using='gin')
    op.drop_table('document_generations')
    op.drop_index(op.f('ix_conversation_summaries_organization_id'), table_name='conversation_summaries')
    op.drop_index('idx_summaries_user_id', table_name='conversation_summaries')
    op.drop_index('idx_summaries_user_agent', table_name='conversation_summaries')
    op.drop_index('idx_summaries_org_user', table_name='conversation_summaries')
    op.drop_index('idx_summaries_org_id', table_name='conversation_summaries')
    op.drop_index('idx_summaries_created_at', table_name='conversation_summaries')
    op.drop_table('conversation_summaries')
    op.drop_index(op.f('ix_bulk_jobs_organization_id'), table_name='bulk_jobs')
    op.drop_index('idx_bulk_jobs_status', table_name='bulk_jobs')
    op.drop_index('idx_bulk_jobs_source_path', table_name='bulk_jobs')
    op.drop_index('idx_bulk_jobs_org_status', table_name='bulk_jobs')
    op.drop_index('idx_bulk_jobs_org_id', table_name='bulk_jobs')
    op.drop_index('idx_bulk_jobs_org_folder', table_name='bulk_jobs')
    op.drop_index('idx_bulk_jobs_created_at', table_name='bulk_jobs')
    op.drop_table('bulk_jobs')
    op.drop_index('idx_organizations_plan_id', table_name='organizations')
    op.drop_index('idx_organizations_is_active', table_name='organizations')
    op.drop_index('idx_organizations_created_at', table_name='organizations')
    op.drop_index('idx_organizations_active_created', table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('subscription_tiers')
    op.drop_index('idx_sessions_refresh_token', table_name='sessions')
    op.drop_index('idx_sessions_organization_id', table_name='sessions')
    op.drop_index('idx_sessions_org_user', table_name='sessions')
    op.drop_index('idx_sessions_org_is_active', table_name='sessions')
    op.drop_index('idx_sessions_expires_at', table_name='sessions')
    op.drop_table('sessions')
